#!/bin/sh

addgroup -g ${GID} lstu && adduser -H -s /bin/sh -D -G lstu -u ${UID} lstu

cd /usr/lstu
mkdir -p data
chown -R lstu:lstu .

# Outputting directly to lstu.conf using "sed -i" when mounted with docker fails.
echo "$(sed \
        -e 's|<secret>|'${SECRET}'|' \
        -e 's|<contact>|'${CONTACT}'|' \
        -e 's|<adminpwd>|'${ADMINPWD}'|' \
        -e 's|<webroot>|'${WEBROOT}'|' lstu.conf
)" > lstu.conf

exec su-exec lstu:lstu /sbin/tini -- /usr/local/bin/carton exec hypnotoad -f /usr/lstu/script/lstu
